keys:
  - &admin age1lmd0gxt00l7nzrusx7tqvhndwvzlanlerd0pred98nr2aepgdc7qu573xh 
  - &babel age1nms5kcqeuke34fuavanx97xcefkr9vn3kguvtv33ugkhcg65836s420u4c
creation_rules:
  - path_regex: secrets/.*$
    key_groups:
    - age:
      - *admin
      - *babel
