font=JetBrainsMono Nerd Font 11
background-color={{colors.surface.default.hex}}f5
text-color={{colors.on_surface.default.hex}}
border-color={{colors.primary.default.hex}}
border-size=2
border-radius=12
padding=16
margin=16
width=380
height=180
default-timeout=6000
max-visible=4
anchor=top-right

[urgency=critical]
default-timeout=0
border-color={{colors.error.default.hex}}

[mode=do-not-disturb]
invisible=1
